// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDwjFS03TIT8t5vSnTRjJmZzluEPV_9Xo',
    appId: '1:1009203996064:web:481422932811604990f0c5',
    messagingSenderId: '1009203996064',
    projectId: 'nagatama-app-d39b8',
    authDomain: 'nagatama-app-d39b8.firebaseapp.com',
    storageBucket: 'nagatama-app-d39b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEFOshXd8bgg7jzzlc1VJDoodhRS52FuA',
    appId: '1:1009203996064:android:505c5e6abb445c9890f0c5',
    messagingSenderId: '1009203996064',
    projectId: 'nagatama-app-d39b8',
    storageBucket: 'nagatama-app-d39b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApueVQphH5wNY7BWoQpk1CO7ax0pipnY',
    appId: '1:1009203996064:ios:caccdedf30342cc790f0c5',
    messagingSenderId: '1009203996064',
    projectId: 'nagatama-app-d39b8',
    storageBucket: 'nagatama-app-d39b8.appspot.com',
    iosClientId: '1009203996064-v3bma3sn5qu0efefhnr36s50esjcalsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.samplePodFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDApueVQphH5wNY7BWoQpk1CO7ax0pipnY',
    appId: '1:1009203996064:ios:caccdedf30342cc790f0c5',
    messagingSenderId: '1009203996064',
    projectId: 'nagatama-app-d39b8',
    storageBucket: 'nagatama-app-d39b8.appspot.com',
    iosClientId: '1009203996064-v3bma3sn5qu0efefhnr36s50esjcalsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.samplePodFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDwjFS03TIT8t5vSnTRjJmZzluEPV_9Xo',
    appId: '1:1009203996064:web:581b08bea0da100990f0c5',
    messagingSenderId: '1009203996064',
    projectId: 'nagatama-app-d39b8',
    authDomain: 'nagatama-app-d39b8.firebaseapp.com',
    storageBucket: 'nagatama-app-d39b8.appspot.com',
  );

}