version: 2

updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directory: "/app"
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directory: "/client"
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directory: "/app_server"
    schedule:
      interval: weekly
