targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/feature/**/**_page.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/router/app_router.dart