services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "v160-251-212-48.aadv.static.cnode.jp -> http://app:8080"
      STAGE: "production"
      WEBSOCKET: "true"
    restart: always
    depends_on:
      - app

  app:
    image: serverpod_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - type: bind
        source: "./.env"
        target: "/.env"
    restart: always
    depends_on:
      - postgres
      - redis

  migrations:
    image: serverpod_app
    volumes:
      - type: bind
        source: "./.env"
        target: "/.env"
    environment:
      - role=maintenance
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sample_pod
      POSTGRES_PASSWORD: "OMIwVoMj1kgFiSaFKJ5ztVyh2zbj7j8C"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "e1LQU3nLRu4QL-tsvcUKaDy5HHaCAWf2"
    environment:
      - REDIS_REPLICATION_MODE=master
