name: app_analyze

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - "**/*.dart"
      - ".github/workflows/app_analyze.yml"
      - "**/pubspec.*"
  workflow_dispatch:

jobs:
  analyze_app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Install dependencies
        run: |
          dart pub get
          dart run melos bootstrap 

      - name: Flutter analyze
        shell: bash
        run: |
          dart run melos analyze

      - name: Setup ruby
        if: ${{ failure() }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run danger
        if: ${{ failure() }}
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: ".github/Gemfile"
          install_path: "vendor/bundle"
          danger_file: ".github/Dangerfile"
          danger_id: "danger-pr"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
